'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RedNodal.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property bmpAfe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpAfe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpConfig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpConfig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpIdentificar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpIdentificar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpNodos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpNodos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpRedNodal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpRedNodal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpReporte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpReporte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpTejido() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpTejido", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se pudo borrar el feature {0} de la base de datos .
        '''</summary>
        Friend ReadOnly Property strErrBorrarFeature() As String
            Get
                Return ResourceManager.GetString("strErrBorrarFeature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se pudo crear el feature {0} en la base de datos .
        '''</summary>
        Friend ReadOnly Property strErrCreacionFeature() As String
            Get
                Return ResourceManager.GetString("strErrCreacionFeature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se pudo conectar con la base de datos. Verifique la ruta de la base de datos en el registro de windows..
        '''</summary>
        Friend ReadOnly Property strErrDBNotFound() As String
            Get
                Return ResourceManager.GetString("strErrDBNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se pudo modificar la base de datos. Verifique que la base de datos puede ser accedida en modo de escritura..
        '''</summary>
        Friend ReadOnly Property strErrDBSoloLectura() As String
            Get
                Return ResourceManager.GetString("strErrDBSoloLectura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El feature {0} no se encuentra en la base de datos .
        '''</summary>
        Friend ReadOnly Property strErrFeatureNoAccesible() As String
            Get
                Return ResourceManager.GetString("strErrFeatureNoAccesible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Falta el campo {0} de la fila {1} en la tabla {2}.
        '''</summary>
        Friend ReadOnly Property strErrInfoFaltante() As String
            Get
                Return ResourceManager.GetString("strErrInfoFaltante", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El campo &quot;{0}&quot;  requiere un valor entero.
        '''</summary>
        Friend ReadOnly Property strErrIntegerRequired() As String
            Get
                Return ResourceManager.GetString("strErrIntegerRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La extensión &quot;Network Analyst&quot; no está disponible para el cálculo de rutas. Se deshabilitará la funcionalidad para la construcción del tejido educativo y de la red nodal..
        '''</summary>
        Friend ReadOnly Property strErrNoExtensionAvalaible() As String
            Get
                Return ResourceManager.GetString("strErrNoExtensionAvalaible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El AFE no contiene ningún proyecto urbano definido. No es posible construir la red nodal.
        '''</summary>
        Friend ReadOnly Property strErrNoProyectoUrbano() As String
            Get
                Return ResourceManager.GetString("strErrNoProyectoUrbano", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se pudo encontrar la configuración de la red nodal en el registro de Windows.
        '''</summary>
        Friend ReadOnly Property strErrRegistryDataNotFound() As String
            Get
                Return ResourceManager.GetString("strErrRegistryDataNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se pudo encontrar la clave &quot;{0}&quot; en el registro.
        '''</summary>
        Friend ReadOnly Property strErrRegistryKeyNotFound() As String
            Get
                Return ResourceManager.GetString("strErrRegistryKeyNotFound", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
